### ISSUE TITLE
Cannot make a service call

### ISSUE THREAD

**Issue by Umut93** [Serviceplatformen/demoservice-client-net#10]
I get an error on calling a service https://digitaliseringskataloget.dk/integration/sf1460b from serviceplatformen with this:

```
<E2ETraceEvent xmlns="http://schemas.microsoft.com/2004/06/E2ETraceEvent">
<System xmlns="http://schemas.microsoft.com/2004/06/windows/eventlog/system">
<EventID>131075</EventID>
<Type>3</Type>
<SubType Name="Error">0</SubType>
<Level>2</Level>
<TimeCreated SystemTime="2021-10-07T07:22:04.1107790Z" />
<Source Name="System.ServiceModel" />
<Correlation ActivityID="{438778e9-2d50-47fa-820b-b9b7af477ce0}" />
<Execution ProcessName="w3wp" ProcessID="10928" ThreadID="11" />
<Channel />
<Computer>XXX</Computer>
</System>
<ApplicationData>
<TraceData>
<DataItem>
<TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Error">
<TraceIdentifier>https://docs.microsoft.com/dotnet/framework/wcf/diagnostics/tracing/System-ServiceModel-Diagnostics-ThrowingException</TraceIdentifier>
<Description>Throwing an exception.</Description>
<AppDomain>/LM/W3SVC/2/ROOT/SI.WS.Core-1-132780648886676155</AppDomain>
<Exception>
<ExceptionType>System.ServiceModel.Security.MessageSecurityException, System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
<Message>Security processor was unable to find a security header in the message. This might be because the message is an unsecured fault or because there is a binding mismatch between the communicating parties.   This can occur if the service is configured for security and the client is not using security.</Message>
<StackTrace>
at System.ServiceModel.Security.SecurityStandardsManager.CreateReceiveSecurityHeader(Message message, String actor, SecurityAlgorithmSuite algorithmSuite, MessageDirection direction)
at System.ServiceModel.Security.MessageSecurityProtocol.CreateSecurityHeader(Message message, String actor, MessageDirection transferDirection, SecurityStandardsManager standardsManager)
at System.ServiceModel.Security.MessageSecurityProtocol.ConfigureReceiveSecurityHeader(Message message, String actor, SecurityProtocolCorrelationState[] correlationStates, SecurityStandardsManager standardsManager, IList`1&amp; supportingAuthenticators)
at System.ServiceModel.Security.AsymmetricSecurityProtocol.VerifyIncomingMessageCore(Message&amp; message, String actor, TimeSpan timeout, SecurityProtocolCorrelationState[] correlationStates)
at System.ServiceModel.Security.MessageSecurityProtocol.VerifyIncomingMessage(Message&amp; message, TimeSpan timeout, SecurityProtocolCorrelationState[] correlationStates)
at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.ProcessReply(Message reply, SecurityProtocolCorrelationState correlationState, TimeSpan timeout)
at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.Request(Message message, TimeSpan timeout)
at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)
at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData&amp; msgData, Int32 type)
at Fujitsu.eDoc.SAPA.BLL.SF1460B.BeskedfordelerPortType.opretvaerdiliste(opretvaerdilisteRequest request)
at Fujitsu.eDoc.SAPA.BLL.ProcessEngine.BatchMessageDistributionMaintainValueListJob.MainTainValueList()
at (Object , Object[] )
at SI.Util.Reflection.ObjectFactory.InvokePublicVisibleOnly(String typeName, String methodName, Object[] args)
at SI.Biz.Core.Dispatch.DispatchImpl.InternalInvokeExecute(InvokeSite inv)
at SI.Biz.Core.Dispatch.DispatchImpl.Paxes.serialWork()
at SI.Biz.Core.Dispatch.DispatchImpl.Paxes.StartWork()
at SI.Biz.Core.Dispatch.DispatchImpl.Batch(String id, String xmlBatch)
at SI.Biz.Core.DispatchManager.Batch(String userName, String batchXml)
at SI.Biz.Core.ProcessEngine.Runtime.Invoke_XML.Execute(Dictionary`2 arguments, Dictionary`2 options)
at SI.Biz.Core.ProcessEngine.Runtime.WorkUnitContainer.Execute(Dictionary`2 arguments, Boolean autoConvertArguments, Dictionary`2 options)
at SI.Biz.Core.ProcessEngine.Runtime.JobExecutor.execute(MonitorInfo queue, WorkUnitContainer uow)
at SI.Biz.Core.ProcessEngine.Runtime.WorkUnitManager.ExecuteJob(String nameOrId)
at SI.Biz.Core.ProcessEngine.Runtime.Stubs.WorkUnitManagerStub.ExecuteJob(String jobId)
at SI.Biz.Core.ProcessEngine.WorkUnitManagerProxy.ExecuteJob(String jobId)
at SI.Biz.Core.Compatibility.WorkUnitManager.&lt;&gt;c__DisplayClass2_0.&lt;ExecuteJob&gt;b__0()
at SI.Biz.Core.Compatibility.LegacyBase.Invoke(String id, Action action)
at SI.Biz.Core.Compatibility.WorkUnitManager.ExecuteJob(String id, String jobId)
at SI.Biz.Core.Compatibility.WorkUnitManager.&lt;&gt;c__DisplayClass3_0.&lt;ExecuteJobAsync&gt;b__1()
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task.Execute()
at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&amp; currentTaskSlot)
at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
</StackTrace>
<ExceptionString>System.ServiceModel.Security.MessageSecurityException: **Security processor was unable to find a security header in the message. This might be because the message is an unsecured fault or because there is a binding mismatch between the communicating parties.   This can occur if the service is configured for security and the client is not using security**.</ExceptionString>
</Exception>
</TraceRecord>
</DataItem>
</TraceData>
</ApplicationData>
</E2ETraceEvent>
```

**Comment by Serviceplatformen** [comment]
Hi

If you still have the isssue please contact helpdesk@serviceplatformen.dk.
We are closing the issue feature.

Regards
ServicePlatformen
